version: '3'

services:
  nodejs:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - HOST=mongo
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - postgres

  postgres:
    image: postgres:14-alpine3.14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgis

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT=80
    ports:
      - '15432:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres


  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    # volumes:
    #     - ./data:/data/db

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - nodejs

volumes:
  db:
  pgadmin:
