# Use the latest official Node.js image as base
FROM node:latest

# Set the working directory inside the container
WORKDIR /backend

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port on which the app will run
EXPOSE 3000

# Command to run the application
#CMD ["npm", "start"]



#CMD ["node", "server.js"]

CMD ["npm", "run", "dev"]

