# Use the latest official Node.js image as base
FROM node:latest

# Set the working directory inside the container
WORKDIR /backend

# Install nodemon globally
RUN npm install -g nodemon

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Create node_modules directory if it doesn't exist
RUN mkdir -p node_modules

# Install dependencies again to ensure everything is in place
RUN npm install --legacy-peer-deps

# Expose the port on which the app will run
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]