name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '22'
#     
#     - name: Install frontend dependencies
#       run: |
#         cd FrontEnd
#         npm ci
#     
#     - name: Build frontend
#       run: |
#         cd FrontEnd
#         ## npm run build
#         npm run dev
#     
#     - name: Install backend dependencies
#       run: |
#         cd backend
#         npm ci
#     
#    ## - name: Run backend tests
#     ##run: |
#       ##  cd backend
#       ## npm test
#     
#     - name: Start backend server
#       run: |
#         cd backend
#         npm run dev &
#         sleep 10

  deploy:
#   needs: test  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /marketplace/marketplace
          git pull
          docker-compose up -d --build
        EOF
