name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' 
    - name: Install dependencies
      run: |
        npm ci
    - name: Run backend tests
      run: |
        cd backend  
        npm test
    - name: Run frontend tests
      run: |
        cd FrontEnd 
        npm run build

  deploy:
    needs: test  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -i deploy_key.pem $SERVER_USER@$SERVER_IP "cd /home/yassine/marketplace/marketplace && git pull && docker-compose up -d --build"
