name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '22'
#     
#     - name: Install frontend dependencies
#       run: |
#         cd FrontEnd
#         npm ci
#     
#     - name: Build frontend
#       run: |
#         cd FrontEnd
#         ## npm run build
#         npm run dev
#     
#     - name: Install backend dependencies
#       run: |
#         cd backend
#         npm ci
#     
#    ## - name: Run backend tests
#     ##run: |
#       ##  cd backend
#       ## npm test
#     
#     - name: Start backend server
#       run: |
#         cd backend
#         npm run dev &
#         sleep 10

  deploy:
#   needs: test  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/yassine/marketplace/marketplace && git pull && docker-compose up -d --build"
