name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '22'
#     
#     - name: Install frontend dependencies
#       run: |
#         cd FrontEnd
#         npm ci
#     
#     - name: Build frontend
#       run: |
#         cd FrontEnd
#         ## npm run build
#         npm run dev
#     
#     - name: Install backend dependencies
#       run: |
#         cd backend
#         npm ci
#     
#    ## - name: Run backend tests
#     ##run: |
#       ##  cd backend
#       ## npm test
#     
#     - name: Start backend server
#       run: |
#         cd backend
#         npm run dev &
#         sleep 10

  deploy:
#   needs: test  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -i deploy_key.pem $SERVER_USER@$SERVER_IP "cd /home/yassine/marketplace/marketplace && git pull && docker-compose up -d --build"

        
